Feature/#15
BCSDLab/KOALA_FRONT_END pull request #23
Opened 2022-01-02 08:21 UTC by daepan

## 개요 
![image](https://user-images.githubusercontent.com/50792467/147869759-53b3f155-a32f-4a83-998f-036f45b15f8e.png)
![image](https://user-images.githubusercontent.com/50792467/147870074-37d634f9-3989-4804-8feb-ca087dd25db3.png)

## 이슈 번호

- closes [#15] 

## 변경사항 
마이페이지 기능 작성: 유저 정보를 받아와서 그에 대한 정보를 통해 상황을 알려줌
UI가 변동될 수 있는 사이드 네비바가 열리는 것을 toggle.js로 스토어에서 관리하기로 기능을 추가하였다.

## 특이사항 
아직 유저정보내에 부족한 정보들이 있다. 유저이미지, 학교 인증 여부 등 유저 상태에 대한 내용등에 대한 설계를 해두었다.

2022-01-03 11:29 UTC, jonghopark95 commented
내일 아침까지 확인하겠습니다

2022-01-03 22:54 UTC, jonghopark95 requested changes

2022-01-03 22:54 UTC, jonghopark95 commented on src/App.js
> +import MyPage from 'pages/myPage';
이제 봤는데 페이지 폴더 내의 컴포넌트들이 다 camelCase 로 되어있네요.
컴포넌트들은 PascalCase 로 만들겠다는 convention 이 있었는데 파일 이름도 이에 맞게 수정해주는게 어떨까요?

```suggestion
import MyPage from 'pages/MyPage';
```

2022-01-03 22:54 UTC, jonghopark95 commented on src/api/index.js
> +export const changeNickName = (nickName) => logined.post('user/nickname', nickName);
6번째 줄은 `Nickname` 인데 해당 line 은 NickName 이네요 
어떤걸 사용해도 무방아지만 통일성있는 네이밍을 작성하시는게 좋아보입니다.

```suggestion
export const changeNickname = (nickname) => logined.post('user/nickname', nickname);
```

2022-01-03 22:54 UTC, jonghopark95 commented on src/api/index.js
> +export const deleteUser = () => logined.patch('user/delete');
허... delete 요청인데 `patch` 메소드를 쓰나요? 백엔드 분들에게 얘기해봐야 할거 같은데...

```suggestion
export const deleteUser = () => logined.delete('user');
```

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/Mypage/AutoLogin.js
> +  const isAutoLogedIn = getCookie('isAuto');
이런 오타 계속해서 나오는 것 같아요. 

```suggestion
  const isAutoLoggedIn = getCookie('isAuto');

```

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/Mypage/AutoLogin.js
> +  //마이페이지에서 자동 로그인 체크시 isAuto를 true로 한다.
별로 좋은 스타일의 주석이 아닌것 같아 보입니다... 주석은 가급적이면 자제하고 정말 필요한 부분에만 사용하시고 코드로 설명하는 편이 좋습니다.

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/Mypage/AutoLogin.js
> +  //마이페이지에서 자동 로그인 체크시 isAuto를 true로 한다.
읽다보니 refresh token 유효기간을 클라이언트 단에서 연장하게 해놨네요...??
refresh token 은 서버가 발급해주는 데 유효기간을 왜 저희가 설정하고 있나요?
그리고 애초에 해당 token 이 담고 있는 payload 에 만료 시간이 있을텐데 저희가 또 설정하는게 무슨 의미가 있을까요?

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/Mypage/AutoLogin.js
> +    });
위에서 말했다시피 해당 로직은 필요 없어보입니다 
token 만료 기간은 클라이언트가 아닌 서버 측에서 관리하는 겁니다

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/SideNavbar/index.js
> +    console.log(isOpen);
PR 올리기 전에 스스로 코드 훑어보고 올려주세요... 오타랑 console.log, 불필요한 로직 너무 많이 보여요

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/SideNavbar/index.js
> +  const isOpen = useSelector((state) => state.toggle.isOpen);
`isSideMenu` 가 있는데 `isOpen` 을 둔 이유는... 뭐 모달 같은 UI 를 관리하기 위함인가요?
둘 중 하나를 지워줘도 될것 같아요

2022-01-03 22:54 UTC, jonghopark95 commented on src/components/SideNavbar/index.js
> +)(SideNavbar);
이건... 뭐죠...? 꼭 필요한 로직인가요?

2022-01-03 22:54 UTC, jonghopark95 commented on src/pages/myPage.js
> +    location.reload();
새로 고침 로직 같아 보이는데 굳이 새로고침 할 필요가 있을까요?
새로고침을 하면 이전에 받아놨던 페이지 리소스들이 다시 초기화되며 불필요한 네트워크 비용을 초래하게 됩니다.
가지고 있던 상태값만 로그인 이전으로 바꿔주면 됩니다

2022-01-03 22:54 UTC, jonghopark95 commented on src/pages/myPage.js
> +  */
주석이 너무 별로예요...
대관님만 알아볼 주석이 아니라 다같이 알아볼 주석을 만들어주세요

```suggestion
  /*
    TODO:
    - 이미지, 닉네임, 학교 인증 여부를 가져오는 로직을 추가해야 합니다.
  */

```

2022-01-03 22:54 UTC, jonghopark95 commented on src/pages/myPage.js
> +  const naviagate = useNavigate();
```suggestion
  const navigate = useNavigate();

```

2022-01-03 22:54 UTC, jonghopark95 commented on src/pages/myPage.js
> +  const logoutClick = useCallback(() => {
logoutClick, resignClick 은 어감이 이상하게 느껴집니다
단순히 리뷰 해결을 위해 수정하는 것이 아니라, 네이밍에 대해 정말 생각하고 만들어주세요
네이밍 관련하여 이전 PR 들이랑 별로 달라진게 없어 보입니다

```suggestion
  const clickLogoutButton = useCallback(() => {

```

```suggestion
  const logout = useCallback(() => {

```

2022-01-04 05:03 UTC, daepan commented on src/components/Mypage/AutoLogin.js
> +    });
제가 몰랐네요. 너무 단순하게 생각했습니다 서버쪽이랑 이야기해보겠습니다.

2022-01-04 09:27 UTC, daepan commented on src/App.js
> +import MyPage from 'pages/myPage';
Page 폴더를 컴포넌트라고 안보고 단순 파일이라고 생각해서 ;; 작성한 걸로 보아 PascalCase가 더 적절해 보입니다

2022-01-04 09:34 UTC, daepan commented on src/components/SideNavbar/index.js
> +)(SideNavbar);
이건 제가 리덕스를 사용할 떄 책에서 위와 같은 로직을 써야 된다고 배워서 작성했는데 지워도 별 상관이 없군요;;

2022-01-04 10:09 UTC, daepan commented on src/pages/myPage.js
> +  const logoutClick = useCallback(() => {
네이밍;;;

2022-01-04 10:10 UTC, daepan commented on src/pages/myPage.js
> +  const logoutClick = useCallback(() => {
나머지두;;;

2022-01-04 13:03 UTC, daepan commented on src/App.js
> +import MyPage from 'pages/myPage';
b66b65e

2022-01-04 13:05 UTC, daepan commented on src/api/index.js
> +export const deleteUser = () => logined.patch('user/delete');
![image](https://user-images.githubusercontent.com/50792467/148063421-b7acf705-507e-430b-a241-4608d3a01e10.png)

2022-01-04 13:05 UTC, daepan commented on src/api/index.js
> +export const deleteUser = () => logined.patch('user/delete');
물어보겠습니다;;

2022-01-04 13:06 UTC, daepan commented on src/components/SideNavbar/index.js
> +)(SideNavbar);
30af9aa

2022-01-04 13:07 UTC, daepan commented on src/components/SideNavbar/index.js
> +  const isOpen = useSelector((state) => state.toggle.isOpen);
af9b8bc

2022-01-04 13:08 UTC, daepan commented on src/components/Mypage/AutoLogin.js
> +    });
ebc2194

2022-01-04 13:08 UTC, daepan commented on src/components/Mypage/AutoLogin.js
> +  //마이페이지에서 자동 로그인 체크시 isAuto를 true로 한다.
ebc2194

2022-01-04 13:08 UTC, daepan commented on src/components/Mypage/AutoLogin.js
> +  const isAutoLogedIn = getCookie('isAuto');
ebc2194

2022-01-04 13:10 UTC, daepan commented on src/pages/myPage.js
> +  const naviagate = useNavigate();
ebc2194

2022-01-04 13:10 UTC, daepan commented on src/pages/myPage.js
> +    location.reload();
ebc2194

2022-01-04 13:11 UTC, daepan commented on src/api/index.js
> +export const changeNickName = (nickName) => logined.post('user/nickname', nickName);
082ffb8

2022-01-04 21:23 UTC, jonghopark95 commented on src/components/Mypage/EditNickName.js
> +  const EditName = () => {
이건 왜 또 함수명이 PascalCase죠?

```suggestion
  const editName = () => {
```

2022-01-04 21:30 UTC, jonghopark95 requested changes

2022-01-04 21:30 UTC, jonghopark95 commented on src/components/Mypage/SchoolAuth.js
> +  const AuthState = useSelector((state) => state.myPage.schoolAuth);
이것도 왜 변수명에 갑자기 PascalCase 쓰는거죠?

2022-01-04 21:30 UTC, jonghopark95 commented on src/pages/MyPage.js
> +const MyPage = () => {
이전 코드 리뷰할 땐 없었는데 갑자기 [해당 커밋](https://github.com/BCSDLab/KOALA_FRONT_END/pull/23/commits/af9b8bcffe0a7f109852853757d3bf44fe750485#) 에서 MyPage 코드가 추가된 커밋이 들어왔네요??

그럼 이전에 제대로 완료도 되지 않은 코드를 PR 올리신건가요? 리뷰어 입장에서 굉장히 화납니다... 
정말 dev 에 머지할 수 있는 코드를 작성하셔서 PR 올리시고 기능 추가는 다른 브랜치에서 작업하시고 새로 PR 올려주세요

2022-01-04 21:30 UTC, jonghopark95 commented on src/pages/MyPage.js
> +  const userInfor = useSelector((state) => state.myPage);
`userInfor` 가 아니라 `userInfo` 여야 하지 않나요?? 전 `Infor` 라는 단어는 살면서 처음봅니다

2022-01-04 21:32 UTC, jonghopark95 commented on src/pages/MyPage.js
> +
flex; 뒤의 z... 진짜 황당할 정도로 오탈자가 많습니다 
저도 시간 써서 PR 리뷰 해주는건데... 이런 부분에서 계속 리뷰다니까 감정도 소모되고 이렇게 시간 쓰는게 맞나 허탈하기까지 합니다
제발 이런 오탈자 가지고 리뷰하지 않게 해주세요 부탁드립니다

2022-01-05 06:43 UTC, daepan commented on src/pages/MyPage.js
> +const MyPage = () => {
파일 이름이 변경되면서  올라가게 된 건데 커밋에서 잘못된 것 같습니다

2022-01-05 06:46 UTC, daepan commented on src/pages/MyPage.js
> +
4ebf5cf

2022-01-05 06:46 UTC, daepan commented on src/pages/MyPage.js
> +  const userInfor = useSelector((state) => state.myPage);
4ebf5cf

2022-01-05 06:46 UTC, daepan commented on src/components/Mypage/SchoolAuth.js
> +  const AuthState = useSelector((state) => state.myPage.schoolAuth);
4ebf5cf

2022-01-05 06:46 UTC, daepan commented on src/components/Mypage/EditNickName.js
> +  const EditName = () => {
4ebf5cf

2022-01-05 06:55 UTC, daepan commented on src/pages/MyPage.js
> +const MyPage = () => {
좀 억울합니다 이거 폴더명 변경되면 처음부터 올라가는 식으로 변경되가지고 이렇게 됬습니다. 제가 커밋하면서 이런경우가 거의 없었는데 죄송합니다.

2022-01-05 09:08 UTC, daepan commented on src/api/index.js
> +export const deleteUser = () => logined.patch('user/delete');
회원 탈퇴기는 하지만 로그 생성 및 문제생성시 복구 등 여러가지를 위해
현재 db에서 회원정보를 삭제하지는 않습니다 회원정보에 해당 정보는 삭제됐다는 칼럼을 만듭니다.
예를 들어 is_deleted 같은 해당 필드를 수정함으로써 삭제를 나타내기에
PATCH 로 method 타입을 설정했습니다
라고 답변 받았습니다. 서버쪽에서 정하게 된거라 아마 이런식으로 갈 것 같습니다

2022-01-05 23:26 UTC, jonghopark95 approved these changes

2022-01-06 06:40 UTC, merged