키워드 목록 페이지  #17
BCSDLab/KOALA_FRONT_END pull request #30
Opened 2022-01-12 13:11 UTC by sangyun5108

## 개요 

키워드 목록 페이지 구현

![스크린샷 2022-01-12 오후 10 00 23](https://user-images.githubusercontent.com/69062776/149145044-fdfc88d9-6948-4eeb-abac-d73ec4b94305.png)

## 이슈 번호

- closes [#17] 

## 변경사항 
- 알림 읽음 처리 기능 구현
- 알림 삭제 기능 구현
- 알림 필터링 기능 구현
- 알림 검색 기능 구현

## 특이사항 
- SideNavbar와 연동은 키워드 관련 페이지 기능 구현 후, 제작 예정입니다.(Toggle에 따른 UI포함)
- 무한 스크롤링 부분은 상의 후, 구현할 예정입니다.

2022-01-13 09:32 UTC, daepan commented on src/api/index.js
> +}
API를 이렇게 묶는 방법 아주 좋은 것 같습니다! 다른 API들도 공통된 속성들을 뭉쳐놔야겠군요

2022-01-13 09:32 UTC, daepan commented on src/constant/index.js
> +
menuItem은 변수네임인 것 같네요. 상수폴더내에 있으니 MENU_ITEM 식으로 명시해주는게 좋을 것 같습니다.
그리고 WEEK 같은 경우에는 다른 곳에서도 사용할 수도 있는 여지가 있지만 menuItem은 키워드 내에만 사용하는 것 같은데 따로 상수 폴더내에 저장하신 이유가 궁금합니다.

2022-01-13 10:15 UTC, sangyun5108 commented on src/constant/index.js
> +
다른 곳에서 사용되는지에 대한 여부를 생각안하고, 단지 상수라는 이유로 빼놓은 것 같습니다. 수정하도록 하겠습니다!

2022-01-13 10:18 UTC, sangyun5108 commented on src/constant/index.js
> +
46d4d42

2022-01-14 00:05 UTC, jonghopark95 requested changes
수정할게 너무 많아보이네요... 수정 사항 반영하시고 다시 PR 날리시는게 좋아보입니다.

- `prettier` 포매팅이 안되어있어 리뷰하기 너무 불편합니다.
- 하나의 컴포넌트에서 모든 것을 관리하려는 경향이 있으신것 같습니다. 컴포넌트 구분을 잘 해주세요
- 네이밍 컨벤션 신경써주세요

2022-01-14 00:05 UTC, pumpkiinbell commented on src/api/index.js
> +  InquiryKeyword : () => logined.get(`/keyword`),
`camelCase` 로 컨벤션 맞춰주시길 바랍니다.

```suggestion
  inquiryKeyword : () => logined.get(`/keyword`),
```

또는 간단히 `getKeyword` 해도 되겠네요
```suggestion
  getKeyword : () => logined.get(`/keyword`),
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/api/index.js
> +  movekeywordList : (data) => logined.post(`/scrap`,{"board_id":data}),
해당 코드를 실행시켜본건 아니라 어떤 문맥에서 post /scrap 요청이 `moveKeywordList` 이 되는 지 모르겠네요
`addScrap` 정도면 되지 않을까요?

```suggestion
  addScrap : (data) => logined.post(`/scrap`,{"board_id":data}),

```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordHeader/index.js
> +    const user = useSelector((state)=>state.auth);
`prettier` 설정이 적용 안되있어 보이네요

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +import { getTitle,makeDeleteQuery } from '../utills';
누가 만들었는지 모르겠지만 파일 이름 수정하는게 좋아보입니다

```suggestion
import { useSelector, useDispatch } from 'react-redux';
import { getKeywordList,deleteKeywordList,moveKeywordItem,readKeywordItem } from 'store/keyword';
import { getTitle,makeDeleteQuery } from '../utils';
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +    },
이런 정보는 `constants` 모듈에 같이 보관하는게 좋아보이네요

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +    const [notReadNotification, setNotReadNotification] = useState(false);
이건 하나의 값으로 관리할 수 있지 않을까요...?
`notRead~~` 는 되게 어색해보이네요

```suggestion
    const [readNotification, setReadNotification] = useState(false);
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +    const [isToggle,setIsToggel] = useState(false);
```suggestion
    const [isToggle,setIsToggle] = useState(false);
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +        }else if(menu === '아우미르'){
switch 문 활용하는게 더 깔끔하겠네요

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +                }
요렇게 줄일 수 있어 보이네요
```suggestion
            const filterList = keywordList.filter((item)=> item.url.includes(AUNURI)));
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +    },[readNotification]);
하나로 묶을 수 있어 보이네요

```suggestion
    const onClickReadNotification = ()=>{
        setReadNotification((prev)=>!prev);
        setNotReadNotification(prev => !prev);
    };
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +        const filterList = list.filter((item)=>{
위에 참고해 수정해주세요

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +        }
`early return case ` 가 더 깔끔해보입니다

```suggestion
        if(isRead) return;
        
        dispatch(readKeywordItem(id));
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +            })
```suggestion
            newCheckListId = checkListId.filter((item)=>item !== id))
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/KeywordList/index.js
> +                    dispatch(moveKeywordItem(id));
굳이 식별자 선언이 필요 없어보이네요

```suggestion
                    dispatch(moveKeywordItem(item.id));
```

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/utills/index.js
> +
개인취향이지만 저는 else if 가독성이 너무 구리다 생각해요
`switch case` 한번 써보시죵

2022-01-14 00:05 UTC, pumpkiinbell commented on src/components/Keyword/utills/index.js
> +        str+=`&notice-id=${i}`;
엥 이 구문은 뭐죠...?
i가 startId 와 같다면 str 에`notice-id` 가 두번 들어갈텐데 의도하신건가요?

2022-01-14 00:05 UTC, jonghopark95 commented on src/store/keyword.js
> +const [GETKEYWORDLIST,GETKEYWORDLIST_SUCCESS,GETKEYWORDLIST_FAILURE] = createRequestSagaActionTypes("keyword/GETKEYWORDLIST");
허허... underscore 없으니 가독성이 정말 안좋네요

```suggestion
const [GET_KEYWORD_LIST,GET_KEYWORD_LIST_SUCCESS,GET_KEYWORD_LIST_FAILURE] = createRequestSagaActionTypes("keyword/GETKEYWORDLIST");
```

2022-01-14 00:05 UTC, jonghopark95 commented on src/constant/index.js
> +// keyword
주석이 어떤 의미인지 모르겠어요

2022-01-14 00:05 UTC, jonghopark95 commented on src/components/Keyword/KeywordList/styles.js
> +                    return '695px';
이 정도면 각 분기마다 함수를 새로 만들어서 wrapping 하는게 더 좋아보입니다

2022-01-14 00:05 UTC, jonghopark95 commented on src/components/Keyword/KeywordList/index.js
> +    const [deleteList, setDeleteList] = useState(false);
이 코드에서 들고 있는 상태가 너무 많네요
컴포넌트 분리해주는게 가독성도 좋고 유지보수도 훨씬 더 용이할겁니다

2022-01-14 05:19 UTC, sangyun5108 commented on src/api/index.js
> +  InquiryKeyword : () => logined.get(`/keyword`),
넵 camelCase 지키도록 하겠습니다.
키워드 조회라는 이름에서 조회를 생각해서 inquiry를 사용했는데, 그냥 get을 사용하는 것이  더 좋은것 같습니다!

2022-01-14 06:49 UTC, sangyun5108 commented on src/api/index.js
> +  InquiryKeyword : () => logined.get(`/keyword`),
3c5adff

2022-01-14 06:51 UTC, sangyun5108 commented on src/api/index.js
> +  movekeywordList : (data) => logined.post(`/scrap`,{"board_id":data}),
post/scrap 요청이 보관함으로 이동시키는 것이여서 movekeywordList로 네이밍 했습니다.
addScrap으로 수정하도록 하겠습니다!

2022-01-14 06:56 UTC, sangyun5108 commented on src/api/index.js
> +  movekeywordList : (data) => logined.post(`/scrap`,{"board_id":data}),
9f14a7e

2022-01-14 06:58 UTC, sangyun5108 commented on src/components/Keyword/KeywordList/index.js
> +import { getTitle,makeDeleteQuery } from '../utills';
제가 만든 파일입니다! 수정하도록 하겠습니다

2022-01-14 06:58 UTC, sangyun5108 commented on src/components/Keyword/KeywordList/index.js
> +import { getTitle,makeDeleteQuery } from '../utills';
86aaf19

2022-01-14 07:00 UTC, sangyun5108 commented on src/components/Keyword/KeywordList/index.js
> +    },
저도 이거 빼놨었는데, 대관님이 공유되지 않는 상수값은 constant에 넣지 말라고 하셔서 다시 수정하도록 하겠습니다!

2022-01-14 07:02 UTC, sangyun5108 commented on src/components/Keyword/KeywordList/index.js
> +    },
91ff530

2022-01-14 07:04 UTC, sangyun5108 commented on src/components/Keyword/utills/index.js
> +        str+=`&notice-id=${i}`;
![스크린샷 2022-01-14 오후 4 03 16](https://user-images.githubusercontent.com/69062776/149465544-585a6602-575e-46f1-b6ec-0c55062c5d53.png)
키워드 알림 여러개 삭제하려면 캡쳐 이미지 같은 형식으로 string을 연달아 보내야해서 저렇게 만들어 사용했습니다!

2022-01-14 07:04 UTC, sangyun5108 commented on src/store/keyword.js
> +const [GETKEYWORDLIST,GETKEYWORDLIST_SUCCESS,GETKEYWORDLIST_FAILURE] = createRequestSagaActionTypes("keyword/GETKEYWORDLIST");
underscore 추가하도록 하겠습니다!

2022-01-14 07:13 UTC, sangyun5108 commented on src/store/keyword.js
> +const [GETKEYWORDLIST,GETKEYWORDLIST_SUCCESS,GETKEYWORDLIST_FAILURE] = createRequestSagaActionTypes("keyword/GETKEYWORDLIST");
8a3e07e

2022-01-14 07:13 UTC, sangyun5108 commented on src/constant/index.js
> +// keyword
keyword관련 페이지에서 사용한다는 의미로 적었는데, 좀더 자세히 적도록 하겠습니다!

2022-01-14 07:14 UTC, sangyun5108 commented on src/constant/index.js
> +// keyword
f5ac617

2022-01-14 07:15 UTC, sangyun5108 commented on src/components/Keyword/KeywordList/index.js
> +    const [deleteList, setDeleteList] = useState(false);
넵! 하나에 다 적지 않고, 최대한 분리해보겠습니다!
리뷰해주셔서 감사합니다

2022-01-15 07:36 UTC, jonghopark95 commented on src/api/index.js
> +  movekeywordList : (data) => logined.post(`/scrap`,{"board_id":data}),
음... 참고로 저는 앞에 접두어를 `create (post) / get / update(put) / delete` 로 통일해서 사용하고자 합니다 
`add` 도 나쁘지 않고요 :) 개발하시면서 상윤님만의 네이밍 원칙을 가지시는 것도 좋겠네요~

2022-01-15 07:38 UTC, jonghopark95 commented on src/api/index.js
> +  InquiryKeyword : () => logined.get(`/keyword`),
아하 그런 경우라면 API 요청부는 요청만을 의미하는 네이밍을 만들고, 
이를 사용하는 함수에서 `inquiryKeyword` 등으로 네이밍 해주면 좋을것 같습니다
API 요청 함수는 `요청` 이라는 문맥만 강조하는게 좋다고 생각합니다~

2022-01-15 07:38 UTC, jonghopark95 commented on src/components/Keyword/KeywordList/index.js
> +import { getTitle,makeDeleteQuery } from '../utills';
😅

2022-01-15 07:39 UTC, jonghopark95 commented on src/components/Keyword/KeywordList/index.js
> +    },
@daepan

2022-01-15 07:41 UTC, jonghopark95 commented on src/components/Keyword/KeywordList/index.js
> +    },
> 저도 이거 빼놨었는데, 대관님이 공유되지 않는 상수값은 constant에 넣지 말라고 하셔서 다시 수정하도록 하겠습니다!

아하... 프로젝트에 그런 원칙이 있으면 PM 의견 따라가는게 좋다고 생각합니다

다만 저는 `constants` 폴더 아래에 특정 도메인으로 묶일 수 있는 상수들은 해당 파일을 만들어 모아두는 편입니다

위의 경우를 예로 들면 `/constants/keyword.js` 가 되겠네요

2022-01-15 07:41 UTC, jonghopark95 commented on src/components/Keyword/utills/index.js
> +
사실 요건 취향 차이긴 한데... 분기가 복잡할 경우는 `else if` 도 적절히 사용하면 좋다고 생각합니다~

2022-01-15 07:45 UTC, jonghopark95 commented on src/components/Keyword/utills/index.js
> +        str+=`&notice-id=${i}`;
오호 그렇군영... 저였다면 map 으로 돌리고 join 을 사용해서 & 연산자 붙여줬을 것 같아요

```js
const ids = [1, 2, 3, ...];

str += ids.map((id) => `notice-id=${id}`).join("&");
```

2022-01-15 07:46 UTC, jonghopark95 commented on src/constant/index.js
> +// keyword
그렇군요 :)

2022-01-15 07:47 UTC, jonghopark95 commented
@sangyun5108 혹시 헷갈리거나 고민되는 부분 있으면 슬랙 DM 보내주세요~ 수고 많으십니다!

2022-01-16 09:34 UTC, jonghopark95 approved these changes

2022-01-16 09:35 UTC, jonghopark95 commented
conflict 해결하고 머지해주세요~ 수고하셨습니다

2022-01-19 02:48 UTC, merged