Feature/#20
BCSDLab/KOALA_FRONT_END pull request #36
Opened 2022-01-19 06:08 UTC by sangyun5108

## 개요 
![스크린샷 2022-01-19 오후 2 53 00](https://user-images.githubusercontent.com/69062776/150073592-672ab4e6-fdca-4969-b6f6-f01bf1dec510.png)

## 이슈 번호

- closes [#20] 

## 변경사항
- 제플린에 나와있는 키워드 수정 관련 기능을 구현

## 특이사항 
- 네비게이션 바와 데이터 연동 추후 구현
- 네비게이션 바에 따른 UI 변경 추후 구현

2022-01-19 13:32 UTC, jonghopark95 commented
conflict 해결부터 먼저 해주시겠어요...?

2022-01-19 13:32 UTC, jonghopark95 commented
PR 이름도 수정해주세요~

2022-01-20 10:00 UTC, sangyun5108 commented
conflict, PR 이름 수정 했습니다!

2022-01-20 13:34 UTC, jonghopark95 commented
저번에 prettier 설정 하라고 하지 않았나요? 
이대로 merge 하면 추후에 다른 분이 같은 페이지 수정하면 prettier formatting 되면서 쓸데 없는 부분까지 diff 생겨서 리뷰하기 불편해져요...
대관님이 .prettierrc 넣어놨는데 왜 쓰질 않으시나요...
prettier 로 만드신 페이지 모두 formatting 하고 다시 리뷰요청해주세요

2022-01-20 13:34 UTC, jonghopark95 requested changes
저번에 prettier 설정 하라고 하지 않았나요? 
이대로 merge 하면 추후에 다른 분이 같은 페이지 수정하면 prettier formatting 되면서 쓸데 없는 부분까지 diff 생겨서 리뷰하기 불편해져요...
대관님이 .prettierrc 넣어놨는데 왜 쓰질 않으시나요...
prettier 로 만드신 페이지 모두 formatting 하고 다시 리뷰요청해주세요

2022-01-24 02:34 UTC, sangyun5108 commented
저번에 prettier 설정한다고 했었는데, 적용 된걸 제대로 확인을 안한것 같습니다..
다시 적용하고 올렸습니다!

2022-01-24 16:14 UTC, jonghopark95 approved these changes

2022-01-24 16:14 UTC, pumpkiinbell commented on src/components/Keyword/KeywordFilter/styles.js
> +      }
나쁘진 않은데 분기가 여러번 생기며 코드 깊이가 다소 깊어진것 같네요
 switch case 사용해도 좋을듯 합니다

2022-01-24 16:14 UTC, pumpkiinbell commented on src/components/Keyword/KeywordFilter/styles.js
> +      return `
분기문으로 나눠지는게 아니라 그냥 `&&` 써도 되겠네요

```suggestion
  ${(props) => props.checkAll && `/* ... */ `
```

2022-01-24 16:14 UTC, pumpkiinbell commented on src/components/Keyword/KeywordFilter/styles.js
> +  color: #999999;
참고차... 연속된 숫자들은 `color: #999;`  이렇게 줄일수도 있습니다

2022-01-24 16:14 UTC, pumpkiinbell commented on src/components/Keyword/ModifyKeyword/index.js
> +  const [alarmTerm, setAlarmTerm] = useState(null);
Alarm 과 관련된 컴포넌트 폴더를 만들고 해당 폴더에서 Alarm 을 관리하는게 좋아보여요
지금은 가독성도 너무 떨어지고, 관심사가 `AddKeyword` 에 섞여서 유지보수가 너무 어려워보여요

2022-01-27 02:53 UTC, daepan requested changes
공유되는 로그인 컴포넌트가 있으니 그부분은 확인해주세요!

2022-01-27 02:53 UTC, daepan commented on src/components/Keyword/KeywordHeader/index.js
>        </S.UserContainer>
이건 아무런 기능이 없는 빈 버튼인 것 같습니다. 예전에 로그인 로그아웃 기능이 있는 Shared/LoginButton 을 미리 생성해두었습니다. 몰랐다면 참고해서 넣으면 좋을 것 같습니다.

2022-01-27 02:58 UTC, daepan commented
그리고 처음 봤는데 폴더구조가 저랑 많이 다르더군요. 기능별로 구별하신것 같은데 페이지가 여러개를 만드는데 기능별로 나누어지니 탐색하기 쉽지는 않더군요. 이건 단순한 저의 의견입니다. 폴더이름도 어느정도 통일되면 보기 좋을 것 같습니다. ex) Keyword~~

2022-01-27 05:43 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +      }
넵! 알겠습니다

2022-01-27 05:44 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +      return `
아 &&써도 가능하네요 감사합니다!

2022-01-27 05:44 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +  color: #999999;
앞으로 줄여서 사용하도록 하겠습니다

2022-01-27 05:45 UTC, sangyun5108 commented on src/components/Keyword/ModifyKeyword/index.js
> +  const [alarmTerm, setAlarmTerm] = useState(null);
Alarm과 관련된 컴포넌트를 분리해보도록 하겠습니다

2022-01-27 05:46 UTC, sangyun5108 commented on src/components/Keyword/KeywordHeader/index.js
>        </S.UserContainer>
로그인 로그아웃과 관련된 버튼은 기능을 다구현한 뒤, 대관님이 만들어 놓으신 버튼을 사용해서 수정하도록 하겠습니다

2022-01-27 05:55 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +      }
f9afbe4

2022-01-27 06:00 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +      }
75170f7

2022-01-27 06:07 UTC, sangyun5108 commented on src/components/Keyword/KeywordFilter/styles.js
> +      return `
3be1689

2022-01-31 09:54 UTC, daepan commented on src/components/Keyword/ModifyKeyword/index.js
> +  const [alreadyRegisterItem, setAlreadyRegisterItem] = useState(false);
```suggestion
  const [isAlreadyRegisterItem, setIsAlreadyRegisterItem] = useState(false);
```
위에 식으로 고치는 것이 좋아 보입니다

2022-01-31 09:57 UTC, daepan approved these changes
앞으로의 개발일정을 생각한다면 이 정도면 될 것 같습니다.  고생하셨습니다.

2022-01-31 09:57 UTC, daepan commented on src/components/Keyword/ModifyKeyword/index.js
> +  const [alreadyRegisterItem, setAlreadyRegisterItem] = useState(false);
변수이름이 조금 뭔지 모르겠군요 이미회원가입아이템? 잘 해석이 되지 않습니다,

2022-02-01 03:40 UTC, sangyun5108 commented on src/components/Keyword/ModifyKeyword/index.js
> +  const [alreadyRegisterItem, setAlreadyRegisterItem] = useState(false);
이미 등록된 아이템 입니다!

2022-02-01 03:48 UTC, HAEROOL approved these changes
수고하셨습니다

2022-02-01 03:49 UTC, merged