비회원 로그인 기능 및 로그인 api 수정
BCSDLab/KOALA_FRONT_END pull request #37
Opened 2022-01-20 04:53 UTC by daepan

## 개요 
![image](https://user-images.githubusercontent.com/50792467/150275038-e9456e7e-39a5-4210-a3d6-b37e4bdde4e3.png)

## 이슈 번호

- closes [#34] 

## 변경사항 
비회원 로그인에 대한 guid 생성기를 추가
비회원인 경우에는 guid 생성기에서 생성된 코드를 device_token으로 사용한다. 이는 또한 쿠키로 저장하여 비회원 로그인에
필요한 정보가 필요할 때 끌어올 수 있다.
회원인 경우에는 device_token을 로그인 시에 사용하고 저장하지 않는다.

## 특이사항 
회원과 비회원을 구분하는 것이 device_token 쿠키의 유무에따라 구별한다.

2022-01-20 13:19 UTC, pumpkiinbell commented on src/api/logined.js
> +
이거... 이해하고 쓰시는건가요? 변수도 한 글자로 되어있어서 가독성도 안좋아요

애초에 코드의 목적이 unique 한 값을 생성하는거면 [uuid](https://www.npmjs.com/package/uuid) 나 [nanoid](https://www.npmjs.com/package/nanoid) 를 쓰는게 더 좋아보여요

2022-01-20 13:19 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +        </S.NoneUserLink>
click 시에 guid 값을 담은 API 를 요청한 후, 성공하면 홈으로 보내줘야 하지 않을까요?
지금 로직은 비동기 요청 성공 여부에 상관없이 무조건 홈으로 가는 것 같아요

2022-01-20 13:19 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +  }, [auth.isLoggedIn]);
사소하지만... 이런 부분은 함수로 빼면 추후 유지보수에 도움이 될 것 하네요
```js
useEffect(() => {
  if(isInvalidAccess()) navigate(-1);
}, [auth.isLoggedIn])

// ...
const isInvalidAccess = () => auth.isLoggedIn && getCookie('device_token') == null;
```

2022-01-20 13:19 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
저 궁금한게... 지금 생성되는 토큰에 아무 정보도 담겨있지 않은 것 같은데
추후에 요걸 어떻게 사용하는 걸까요?

2022-01-20 13:19 UTC, jonghopark95 commented on src/store/auth.js
> +const [NON_MEMBER, NON_MEMBER_SUCCESS, NON_MEMBER_FALIURE] = createRequestSagaActionTypes('auth/NON_MEMBER');
취향 차인데...`NON_MEMBER` 보단 `GUEST` 가 가독성 면에서 더 도움이 될 것 같아요  
```suggestion
const [GUEST_LOGIN, GUEST_LOGIN_SUCCESS, GUEST_LOGIN_FAIL] = createRequestSagaActionTypes('auth/NON_MEMBER');

```

2022-01-20 13:19 UTC, jonghopark95 commented on src/components/Auth/LoginForm.js
> +    dispatch(login({ deviceToken, account, password }));
재사용 되지 않는다면 굳이 식별자로 선언할 필요가 있나 싶네요...!

```suggestion
    removeCookie('device_token');
    dispatch(login({ deviceToken: guid(), account, password }));
```

2022-01-20 13:19 UTC, jonghopark95 commented on src/store/auth.js
> +        path: '/',
제가 redux-saga 를 안써봐서 잘 모르겠는데, 이거 `setRefreshToken` 힘수가 전역 상태로 섞여 들어가는거 아닌가요? 
`NON_MEMBER` 비동기 요청이 성공하면 어떻게 굴러가는지 코멘트로 설명해주셨으면 좋겠네요~

2022-01-20 16:49 UTC, daepan commented on src/store/auth.js
> +        path: '/',
비동기 요청에 대해서는 작성해두겠습니다. setRefreshToken함수가 전역상태로 섞이지 않고 undefined라는 값으로 저장됩니다. 함수를 저장하는 것이 아닌 함수만 실행된 상태로 setRefreshToken : undefined로 저장됩니다 
redux-logger로 확인한 부분입니다

2022-01-20 17:01 UTC, daepan commented on src/api/logined.js
> +
긁어온 부분은 죄송합니다;; 혼자서 짜기에는 시간도 시간이지만 저정도 퀄리티는 안나올꺼라고 생각해서 일단은 작성해뒀습니다 공부를 더 해두겠습니다

2022-01-20 17:02 UTC, daepan commented on src/components/Auth/Login.js
> +        </S.NoneUserLink>
비회원 로그인이 실패하는 경우를 생각안하면서 작성해둔 것 같습니다; 확인하고 수정하겠습니다

2022-01-20 17:03 UTC, daepan commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
deviceToken이 담기게 되는데 다시 한번 쿠키 확인해보겠습니다.

2022-01-20 17:24 UTC, daepan commented on src/api/logined.js
> +
bee19c5 uuid로 네이밍 변경하였고 밑에 로직에 대한 변수이름도 수정했습니다

2022-01-20 17:25 UTC, daepan commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
bee19c5 이제 토큰에 정보가 담기게 됩니다 토큰을 생성하는 것과 그에 대해서는 위에 사진 첨부로 설명 작성하였습니다

2022-01-20 17:26 UTC, daepan commented on src/components/Auth/LoginForm.js
> +    dispatch(login({ deviceToken, account, password }));
앗 이 부분은 생각못했습니다. 알맞게 수정하겠습니다

2022-01-20 17:31 UTC, daepan commented on src/components/Auth/LoginForm.js
> +    dispatch(login({ deviceToken, account, password }));
d75a572 회원 로그인에 대한 토큰 저장은 위와 같이 수정했습니다. 비회원 로그인에서는 deviceToken 값을 쿠키에 저장해야되서 일단은 그대로 두었습니다

2022-01-20 17:32 UTC, daepan commented on src/components/Auth/Login.js
> +  }, [auth.isLoggedIn]);
훨씬 더 깔끔하고 보기 좋은 것 같습니다! 참고해서 수정하겠습니다

2022-01-21 01:33 UTC, jonghopark95 commented on src/api/logined.js
> +
아뇨 저도 사실 많이 긁어와요 ㅋㅋ 다만 var 를 let 으로 수정하는거나 지역변수 네이밍 수정정도는 할수 있지 않았나 해서요~ 정규식 부분도 이해하기 어려우셨을거 같아서 말해봤네요

2022-01-21 01:34 UTC, jonghopark95 commented on src/api/logined.js
> +
그리고 uuid 는 네이밍 수정이 아니라 패키지 설치하셔서 사용하는게 어떤가 하고 여쭤본거예요~

2022-01-21 01:36 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +        </S.NoneUserLink>
네엡 아마 to prop 지워주시고 useRouter (v6는 useNavigate 인가요?) 로 성공시에 router push 해주셔야 할거예요

2022-01-21 01:36 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +        </S.NoneUserLink>
Link 태그는 필요없어지면서 a 태그로 바꾸고 preventDefault 해줘야할수도 있어보여요

2022-01-21 01:37 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +        </S.NoneUserLink>
로직이 약간 복잡해지며 이런 케이스가 재활용될수 있으니 따로 컴포넌트로 분리해도 좋겠네요

2022-01-21 01:38 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +  }, [auth.isLoggedIn]);
다행이네요~ 다른 코드 작성하실때도 이런부분들 고민해서 작성하면 더 깔끔한 코드 작성하실 스 있을것 같아유

2022-01-21 01:41 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
어… 저번이랑 달라진게 별로 없는거 같은데요
지금 토큰은 어떤 정보를 암호화하는게 아니라 그냥 랜덤 문자열 발급하는거 아닌가요?

2022-01-21 01:41 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
클라이언트에서 토큰 발급해주려면 이거 복호화도 필요해보이는데…

2022-01-21 01:42 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
갠적으로 이거 굳이 토큰 발급이 필요한가 싶어요 그냥 토큰없이 isLoggedIn 상태만 true로 바꿔주고 권한 필요한 요청은 어따피 토큰이 없으니 로그인 안내를 해주면 되지 않나요?

2022-01-21 01:43 UTC, jonghopark95 commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
저 로직 만드신 이유 설명해주시면 좋겠네요~

2022-01-21 01:45 UTC, jonghopark95 commented on src/store/auth.js
> +        path: '/',
흠… 사가에서 자주 쓰이는 패턴인가요 ??

2022-01-21 01:45 UTC, jonghopark95 commented on src/store/auth.js
> +        path: '/',
undefined 더라도 어쨌든 전역 상태 객체 프로퍼티로 담기게 되는거 아닌가요??

2022-01-21 01:48 UTC, jonghopark95 commented on src/store/auth.js
> +        path: '/',
함수 호출이 의도라면 nonLoginSaga 내의 로직으로 처리할 수 있어보이는데 객체 내에서 실행 시키는 이유가 있나 궁금해서요~

2022-01-21 08:24 UTC, daepan commented on src/store/auth.js
> +        path: '/',
성공하게 된다면 이에 대한 처리를 한다고 생각해서 위와 같이 작성하였고 또한 그게  더 이해가 쉬울 것 같아서였습니다. nonLoginSaga내부에서 처리하는 부분은 생각하지 못했는데 한 번 시도 해보겠습니다

2022-01-21 08:40 UTC, daepan commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
만들게 된 이유는 디바이스 토큰을 통해 로그인하는 것이지만 웹에서는 디바이스 토큰이 필요한 기능 수행하지 않습니다. 그래서 디바이스 토큰을 사용하지 않는 대신에 유니크한 수를 디바이스 토큰을 대신해서 보내줘야한다고 생각해서 uuid 함수를 작성했습니다.

2022-01-21 08:43 UTC, daepan commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
> 갠적으로 이거 굳이 토큰 발급이 필요한가 싶어요 그냥 토큰없이 isLoggedIn 상태만 true로 바꿔주고 권한 필요한 요청은 어따피 토큰이 없으니 로그인 안내를 해주면 되지 않나요?

이 부분에 대해서는 회원 로그인과 비회원 로그인에서의 Refresh API가 동일해서 그에 대한 구별점이 더 필요하다고 생각했습니다

2022-01-21 09:01 UTC, daepan commented on src/components/Auth/Login.js
> +    dispatch(nonMemberLogin(device));
아 그리고 제가 하나 잘못 생각한 부분이었는데 device_token의 유무가 아닌 회원과 비회원에 대한 고유값을 uuid 함수를 통해 만들고 회원인 유저는 회원 고유값을 쿠키에 들고 있어야하고 비회원인 경우에는 비회원 고유값을 들고 있어야 하는 것이 맞는 것 같습니다.

2022-01-21 14:32 UTC, daepan commented
제가 deviceToken에 대한 대체제로 uuid 생성기를 추가하였고 하나의 기기에 대해서 처음 접속하였을 떄 로컬스토리지에 기기에 대한 user_token을 저장합니다.
그리고 비회원 로그인을 누르게 되는 경우는 user_token을 통해 비회원 로그인을 하게 됩니다.
회원 로그인의 경우에는 똑같이 user_token을 보내지만, 계정 아이디와 비밀번호를 요구합니다.
사용자가 로그인되지 않은 상태에서 다른 페이지를 접속하려는 경우 다시 로그인 페이지로 돌려보내는 useAuth 훅을 새로 추가하였습니다.

2022-01-22 03:18 UTC, daepan commented on src/store/auth.js
> +const [NON_MEMBER, NON_MEMBER_SUCCESS, NON_MEMBER_FALIURE] = createRequestSagaActionTypes('auth/NON_MEMBER');
5769597 GUEST가 좀더 어울리는 것 같습니다

2022-01-22 06:33 UTC, jonghopark95 requested changes
-

2022-01-22 08:24 UTC, daepan commented on src/App.js
> +
인증된 페이지에 대한 함수를 Route 함수내에 포함시켜 이를 컨트롤합니다
(Naviagate를 사용하니 Routes안에는 무조건Route가 있어야한다는 RouteError가 발생합니다. )
그래서 위와같이 수정하였습니다

2022-01-22 08:24 UTC, daepan commented on src/App.js
> +        </Route>
이렇게 인증되어야 하는 Route를 감싸주게되면 isLoggedIn이 아직 정해지지 않은 경우 로딩을 보여주게됩니다.
isLoggedIn : true => 로그인이 성공하였기에 밑에 페이지를 접속이 가능합니다
isLoggedIn : false => 로그인이 실패하였기에 로그인페이지로 다시 돌아가게 됩니다.

2022-01-22 09:10 UTC, daepan commented on src/store/auth.js
> +
setToken이라는 함수를 통해 리프레시 토큰과 액세스 토큰에 대한 처리를 하였습니다

2022-01-22 09:10 UTC, daepan commented on src/store/auth.js
> +  yield takeLatest(GUEST_SUCCESS, setToken);
나머지 토큰을 저장해야하는 곳에도 적용하였습니다

2022-01-23 06:48 UTC, jonghopark95 approved these changes
코멘트 남겼는데, 수정하시고 merge 하시면 될것 같아요
수고하셨습니다~

2022-01-23 06:48 UTC, jonghopark95 commented on src/App.js
> +  if (isLoggedIn === null) {
isLoggedIn은 무조건 초기 프로퍼티에 들어가있게 되나요??
혹시 `undefined` 일 케이스는 없나요?

2022-01-23 06:48 UTC, jonghopark95 commented on src/App.js
> +
좋네요 다만 스펠링이... `AuthorizedRoute` 여야 할것같고요
이런 경우엔 `PrivateRoute` 라는 네이밍을 자주 봤습니다.

2022-01-23 06:48 UTC, jonghopark95 commented on src/App.js
> +        </Route>
확인요~ 다만 `접속이 가능` 하다는 표현보단 `렌더링이 가능` 하다는 표현이 더 적합할것 같아요

2022-01-23 06:48 UTC, jonghopark95 commented on src/store/auth.js
> +  yield takeLatest(GUEST_SUCCESS, setToken);
훨씬 좋아보여요~

2022-01-23 09:59 UTC, daepan commented on src/App.js
> +  if (isLoggedIn === null) {
`[LOGIN]: (state) => ({
      ...state,
      isLoggedIn: null,
      authError: null,
    }),`
리덕스 사가에 위와 같은 코드를 넣어 로그인이나 새로고침 등이 이루어질 경우 초기값을 null로 지정해두어서 undefined가 되는 경우는 없을 겁니다!

2022-01-23 12:37 UTC, merged