Feature/#16
BCSDLab/KOALA_FRONT_END pull request #46
Opened 2022-02-07 04:59 UTC by HAEROOL

## 개요 
![image](https://user-images.githubusercontent.com/71335694/152726907-f853a60a-acad-4808-8e86-cddc5d1fa6fa.png)
![image](https://user-images.githubusercontent.com/71335694/152726972-0e4779d0-f447-4099-88c0-c6725f854251.png)

## 이슈 번호

- closes [#16] 

## 변경사항 
보관함/히스토리 기능 구현완료
sideNavBar 적용 예정

## 특이사항

2022-02-07 12:30 UTC, daepan commented
먼저 conflict 해결해주시고 구현된 기능들도 작성해주시면 감사하겠습니다. 1000줄 코드라 조금 빡세군요

2022-02-07 12:44 UTC, HAEROOL commented
> 먼저 conflict 해결해주시고 구현된 기능들도 작성해주시면 감사하겠습니다. 1000줄 코드라 조금 빡세군요

넵 확인했습니다. 처리 후 다시 요청하겠습니다.

2022-02-15 14:25 UTC, ChoiWonBeen commented
오우.. 모든 파일들이 다 갱신됐네요? 52000+이라..
git reset --mixed 를 사용해서  스테이징이 꼬인 파일들은 변화가 없던 시점으로 돌리는 게 나을 것 같네요.
커밋도 너무 많아서 문제가 발생해서 **특정 시점**으로 돌리려 해도 해당 시점을 찾기가 더 힘들어질 것 같아요. 
커밋 주기를 조금 늘려보는 연습을 해보시죠!

2022-02-16 07:05 UTC, daepan requested changes
전체적으로 너무 코드가 많아서 보기 어려웠네요. 다음부터는 단계적으로 pullrequest를 날리고 issue를 분할해서 작업하는 것이 좋을 것 같습니다.  style에 theme.color는 신경써주세요!

2022-02-16 07:05 UTC, daepan commented on src/components/History/History/HistoryContent.js
> +  const isMobile = useMediaQuery({ query: `(max-width:${theme.deviceSizes.mobileL}` });
이 부분 제가 라이브러리 의존성 줄이려고 커스텀 훅을 추가해뒀는데 나중에 리팩토링 기간에 수정하면 좋겠습니다

2022-02-16 07:05 UTC, daepan commented on src/components/History/Scrap/MobileScrapAlert.Style.js
> +    padding: 8px;
theme.color 사용으로 수정 부탁드립니다

2022-02-16 07:05 UTC, daepan commented on src/store/scrap.js
> +const [WRITEMEMO, WRITEMEMO_SUCCESS, WRITEMEMO_FAILURE] = createRequestSagaActionTypes('scrap/WRITEMEMO');
```suggestion
const [GET_SCRAP_LIST, GETS_CRAP_LIST_SUCCESS, GET_SCRAP_LIST_FAILURE] = createRequestSagaActionTypes('scrap/GET_SCRAP_LIST');
const [DELETE_SCRAP_ITEM, DELETE_SCRAP_ITEM_SUCCESS, DELETE_SCRAP_ITEM_FAILURE] =
  createRequestSagaActionTypes('scrap/DELETE_SCRAP_ITEM');
const [GET_MEMO, GET_MEMO_SUCCESS, GET_MEMO_FAILURE] = createRequestSagaActionTypes('scrap/GET_MEMO');
const [FIX_MEMO, FIX_MEMO_SUCCESS,FIX_MEMO_FAILURE] = createRequestSagaActionTypes('scrap/FIX_MEMO');
const [WRITE_MEMO, WRITE_MEMO_SUCCESS, WRITE_MEMO_FAILURE] = createRequestSagaActionTypes('scrap/WRITE_MEMO');
```
요렇게 하면 가독성이 좋을 것 같습니다

2022-02-16 07:05 UTC, daepan commented on src/components/History/LogouButton.js
> +    </>
Shared 폴더에 로그인 버튼이 있으니 활용해서 넣어주시면 감사하겠습니다. 파일이름 LogouButon은 오타인 것 같습니다.

2022-02-16 07:12 UTC, daepan commented
리뷰어 request 다른분들도 부탁드립니다 approve하는 인원이 3명이상이여야 merge가 이루어집니다

2022-02-16 07:21 UTC, crazy-oung reviewed
아직 다 보진 않았는데 뭔가 바뀐 게 없는 파일이 수정이 되었다고 인식이 되는 모양입니다..
혹시 왜 그러는건지 알 수 있을 까요..? ㅠ,ㅠ 
코드에 대한 리뷰는 오늘 8시 회의 끝나는대로 보고 코멘트 달아 드리겠습니다 !

2022-02-19 13:19 UTC, HAEROOL commented on src/store/scrap.js
> +const [WRITEMEMO, WRITEMEMO_SUCCESS, WRITEMEMO_FAILURE] = createRequestSagaActionTypes('scrap/WRITEMEMO');
변경 완료 했습니다.

2022-02-19 13:19 UTC, HAEROOL commented on src/components/History/Scrap/MobileScrapAlert.Style.js
> +    padding: 8px;
theme 적용 완료 했습니다

2022-02-19 13:20 UTC, HAEROOL commented on src/components/History/LogouButton.js
> +    </>
버튼 추가 완료 했습니다.

2022-02-21 13:15 UTC, daepan approved these changes
전체적으로 기능 테스트하시고 정상작동하면 머지해주세요.

2022-02-22 03:22 UTC, merged