키워드 설정 페이지, sideNavBar 연동하기
BCSDLab/KOALA_FRONT_END pull request #47
Opened 2022-02-07 08:29 UTC by sangyun5108

## 개요 

## 이슈 번호

- closes [#28] 

## 특이사항 
- isToggle을 사용한 sideNavBar의 UI 변경에 따른 페이지 밀림 구현 x
- 키워드 설정 페이지 UI만 제작

2022-02-07 13:03 UTC, daepan requested changes
수고하셨습니다 일단 전체적으로 반응형은 되어 있지 않아서 모바일 스타일 들어갈 때 손봐야할 것 같습니다. 
그리고 윈도우랑 맥차이떄문인지 로그인 버튼 저는 한줄로 잘 나오지 않더군요 한번 확인해주시면 감사하겠습니다.
키워드 설정쪽에서 asset/~~ 식으로 작성한 부분에서 이미지가 나오지 않고 있으니 이쪽 부분도 수정 바랍니다.

2022-02-07 13:03 UTC, daepan commented on src/App.js
> +        </Route>
```suggestion
        <Route element = {<AuthorizedRoute/>}>
        <Route exact path="chat/*" element={<ChatPage/>} >
        ~~~
        </Route>
        <Route path="keyword/*" element={<KeywordPage />}>
          <Route index element={<KeywordFilterBar />}></Route>
          <Route path="create" element={<AddKeyword />}></Route>
          <Route path="modify" element={<ModifyKeyword />}></Route>
          <Route path="setting" element={<SettingKeyword />}></Route>
        </Route>
        </Route>
```
키워드 페이지는 로그인된 회원만 접속해야되는 아래 채팅페이지 처럼 로그인된 상태에서만 접속할 수 있도록 감싸주면 더 좋을 것 같습니다.

2022-02-07 13:03 UTC, daepan commented on src/components/Keyword/AddKeyword/index.js
> +  const [alreadyRegisterKeyword, setAlreadyRegisterKeyword] = useState(false);
```suggestion
  const [isRegisterItem, setIsRegisterItem] = useState(false);
  const [isRegisterKeyword, setIsRegisterKeyword] = useState(false);
```
boolean 값을 다루니 이런식으로 작성하는게 더 좋을 것 같습니다.

2022-02-07 13:03 UTC, daepan commented on src/components/Keyword/AddKeyword/styles.js
> +  padding-left: 24px;
border가 두번 들어갔습니다. 그리고 theme.colors 저도 잘 까먹는 부분이지만 themeProvider를 추가해둔거니 꼭 사용해주시면 감사하겠습니다,

2022-02-07 13:03 UTC, daepan commented on src/components/Keyword/AddKeyword/styles.js
> +`;
어떤 부분에서는 return을 사용하시고 어떤부분에서는 return을 사용하지 않으시는데 혹시 차이점을 알 수 있을 까요?

2022-02-07 13:03 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
>          </S.Set>
```suggestion
        <S.Set to="mypage">
          <S.SetText>설정</S.SetText>
        </S.Set>

```
마이페이지부분으로 수정해주시면 감사하겠습니다.

2022-02-07 13:04 UTC, daepan commented
그리고 업데이트된 화면 올려주시면 화면 비교에 용이하니 꼭 올려주세요!

2022-02-07 13:08 UTC, sangyun5108 commented on src/App.js
> +        </Route>
넵! 감싸주도록 하겠습니다

2022-02-07 13:08 UTC, sangyun5108 commented on src/components/Keyword/AddKeyword/index.js
> +  const [alreadyRegisterKeyword, setAlreadyRegisterKeyword] = useState(false);
앞으로 Boolean 값 작성시 is를 사용하도록 하겠습니다

2022-02-07 13:09 UTC, sangyun5108 commented on src/components/Keyword/AddKeyword/styles.js
> +  padding-left: 24px;
아 themeProvider로 수정해보겠습니다!

2022-02-07 13:09 UTC, sangyun5108 commented on src/components/Keyword/AddKeyword/styles.js
> +`;
차이점은 없습니다 수정하도록하겠습니다!

2022-02-07 13:10 UTC, sangyun5108 commented on src/components/SideNavbar/SideNavMenu.js
>          </S.Set>
넵 수정하도록 하겠습니다!

2022-02-07 13:10 UTC, sangyun5108 commented on src/components/SideNavbar/SideNavMenu.js
>          </S.Set>
리뷰 감사합니다!

2022-02-09 04:54 UTC, sangyun5108 commented on src/App.js
> +        </Route>
[faed626](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/faed62688bafedc800505b35fb0fa771cd5b367c)

2022-02-09 04:55 UTC, sangyun5108 commented on src/App.js
> +        </Route>
[c637672](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/c6376721af36aefa485d7e652a2a0bea71548634)

2022-02-09 05:04 UTC, sangyun5108 commented on src/App.js
> +        </Route>
[5d612b0](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/5d612b07ae8edaa87ec66c7ecb1d9fcc88ebb466)

2022-02-09 05:08 UTC, sangyun5108 commented on src/components/Keyword/AddKeyword/index.js
> +  const [alreadyRegisterKeyword, setAlreadyRegisterKeyword] = useState(false);
[8daeb6c](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/8daeb6c17c581cac1832366d507f754f89b3cf66)

2022-02-09 05:22 UTC, sangyun5108 commented on src/components/Keyword/AddKeyword/styles.js
> +`;
[e74f7f6](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/e74f7f6916c374dbf0ed2cb7cf56aa09143f50e8)

2022-02-09 05:28 UTC, sangyun5108 commented on src/components/SideNavbar/SideNavMenu.js
>          </S.Set>
[c17e721](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/c17e7214702c738b41ad8011ffa880361528eca4)

2022-02-09 13:05 UTC, daepan commented on package.json
> +    "react-intersection-observer": "^8.33.1",
혹시 이거 어디서 사용하셨는지 알려주실 수 있나요? 라이브러리 사용 흔적이 없는 것 같은데 한번 확인해주세요

2022-02-10 04:37 UTC, sangyun5108 commented on package.json
> +    "react-intersection-observer": "^8.33.1",
둘다 제거 할게요

2022-02-10 04:42 UTC, sangyun5108 commented on package.json
> +    "react-intersection-observer": "^8.33.1",
[32d02d6](https://github.com/BCSDLab/KOALA_FRONT_END/pull/47/commits/32d02d637d1c7927513127e192c10bae5e3fefb7)

2022-02-10 04:47 UTC, HAEROOL approved these changes
수고하셨습니다

2022-02-10 12:50 UTC, crazy-oung approved these changes
색상 코드가 HEX인게 많네요 theme 써주셨으면 좋겠습니다
어떤 컴포넌트는 HEX값 쓰고 어떤 컴포넌트는 HEX 값을 혼란이 올 거같습니다 
approve는 미리 해두겠습니다

2022-02-10 12:50 UTC, crazy-oung commented on src/pages/KeywordPage.js
> +          <Route path="mypage" element={<SettingKeyword />}></Route>
```suggestion
          <Route path="mypage" element={<SettingKeyword />}/>
```
이렇게 쓸 수도 있을거 같습니다.

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/SettingKeyword/styles.js
> +  color: #fff;
color 값 fff와 222, c4c4c4 모두 theme 에 있습니다..! 이파일에 색상값들이 다 hex코드로 되어 있네용 ..

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/ModifyKeyword/index.js
> +        <S.InputKeyword>{keywordName}</S.InputKeyword>
아래 InputSite 와 이 input이랑 이름이 KeywordInput나 SiteInput 이라고 쓰는게 더 좋지않았나 하는 생각을 해보았습니다..

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/KeywordModal/index.js
> +      {selectItemId && showModal ? (
false 일 때 빈 container 라면 3항 연산자를 사용하는 대신
```suggestion
      {selectItemId &&  (
```
이렇게 쓸 수도 있겠네요

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/KeywordModal/index.js
> +const EditTitie = styled.span``;
오타가 있네요
```suggestion
const EditTitle = styled.span``;
```

혹시 DeleteTitle 과 EditTitle 스타일이 둘다 동일하다면 모달이니까 그냥 Title로 통일하는게 나을거 같습니다.

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/AddKeyword/styles.js
> +  background: ${theme.colors.darkgray};
상단에 theme import 받아서 써도 되지만 ThemeProvier 로 이미 제공을 하고 있어서 props로 부터 가져올 수 있습니다.

```suggestion
  background: ${(props) => props.theme.colors.darkgray};
```

2022-02-10 12:50 UTC, crazy-oung commented on src/components/Keyword/AddKeyword/styles.js
> +        border:1.5px solid #ffd25d;
#ffd25d 값도  theme.colors.yellow 로 지정되어 있습니다

2022-02-16 07:06 UTC, daepan approved these changes

2022-02-16 11:45 UTC, merged