Feature/#41
BCSDLab/KOALA_FRONT_END pull request #48
Opened 2022-02-08 22:32 UTC by crazy-oung

## 개요 
<div style="display: flex">
<img src="https://user-images.githubusercontent.com/29310767/153086375-a58bd31c-aa59-4078-9891-5bdc737e5b69.png" width="45%">
<img src="https://user-images.githubusercontent.com/29310767/153086303-9306b32c-fe25-4634-ae3b-a20af945510a.png" width="45%">

</div>

## 이슈 번호

- closes [#41] 

## 변경사항 
- 약관동의 모바일 화면 작성
- 회원가입 정보 기입폼 페이지 모바일 화면 작성

## 특이사항 
모바일 화면 제목이랑 PC화면 다른 점을 TItleSection 컴포넌트 만들어서 사용했습니다.

2022-02-09 10:41 UTC, daepan requested changes
한번 확인해주시고 수정하실 부분은 수정해주세요~

2022-02-09 10:41 UTC, daepan commented on src/components/Auth/index.js
> +  console.log();
console 삭제 빼먹으신 듯 합니다,

2022-02-09 10:41 UTC, daepan commented on src/components/Shared/TitleSection.js
> +};
location에 따른 출력으로하셨네요. props로 사용하는 방법이 재사용성도 높히고 더 좋을 것 같기도 한데 이렇게 하신 이유가 궁금합니다.

2022-02-09 13:27 UTC, crazy-oung commented on src/components/Auth/index.js
> +  console.log();
헉 제거하겠습니다

2022-02-10 04:45 UTC, sangyun5108 approved these changes

2022-02-10 06:16 UTC, crazy-oung commented on src/components/Shared/TitleSection.js
> +};
`<TitleSection title="회원가입" />` 처럼 쓰기보단 한 컴포넌트에서 관리하는게 편리하다고 생각해서 location을 사용해서 제목을 한번에 관리해주려고 했습니다 나중에 title 변경이 있을 때 용이 할거라 생각해서 이렇게 사용했는데 props를 쓰면 외부 컴포넌트에서 어떤 제목으로 이 TitleSection 을 썼는지 알 수 있을 거같아서 좋을 거 같긴하네요 
변경 해보겠습니다~

2022-02-12 12:28 UTC, HAEROOL approved these changes
수고하셨습니다!

2022-02-16 07:07 UTC, daepan approved these changes

2022-02-21 13:16 UTC, daepan commented
conflict 수정해주시고 머지해주세요

2022-02-22 03:55 UTC, merged