Feature/#4
BCSDLab/KOALA_FRONT_END pull request #6
Opened 2021-12-02 03:45 UTC by daepan

## 개요 
![image](https://user-images.githubusercontent.com/50792467/144353738-88271fde-cc4b-4cd0-b92a-30d1cc91f57d.png)

## 이슈 번호

- closes [#4] 

## 변경사항 
사이드네비게이션 바 웹 퍼블리싱 작업
## 특이사항 
추후 리팩토링시 컴포넌트 분리할 예정
아직 테스트용 계정이 없고 로그인 기능 이후 추가 구현 예정

2021-12-02 03:55 UTC, jonghopark95 commented
하는 일이 있어 저녁에 확인하겠습니다

2021-12-02 09:36 UTC, jonghopark95 requested changes
생각보다 많이 심각하네요... 리뷰들 꼼꼼히 읽어보시고 다 수정하세요
스스로 코드에 대한 책임감이 있어야 합니다.

이미지에는 코멘트를 달 수가 없어서 못달았는데,
왜 `png` 를 `1, 2, 3배 ` 한 모든 것들을 assets 에 넣으신거죠?
그리고 `svg` 를 쓰는것이 더 좋습니다. `png, svg` 차이 모르시면 찾아서 학습하셔요

2021-12-02 09:36 UTC, jonghopark95 commented on public/index.html
> +    <script type="text/javascript" src="vendor/jquery/jquery.js"></script>
이건 뭐죠...? `jquery` 쓰나요...? `vendor` 는 어디 경로에 있죠...?

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +import SidenavMenu from './SidenavMenu';
이렇게 쓸거면 eslint 걷어내는 게 좋습니다.
좀더 코드 스타일에 익숙해지고, eslint 사용하는게 좋아보이네요

2021-12-02 09:36 UTC, jonghopark95 commented on src/App.js
> +      <Route path="/mypage" component={myPage} exact />
중복되는 path 가 없어 `exact` 속성을 굳이 안써도 좋을것 같습니다.

```suggestion
      <Route path="/history" component={historyPage} />
      <Route path="/chat" component={chatPage} />
      <Route path="/keyword" component={keywordPage} />
      <Route path="/mypage" component={myPage} />
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  height: 21px;
스타일 코드가 로직과 섞여있어 너무 어지럽네요
컴포넌트 폴더 내에 `styles.ts` 를 두고 import 하는게 좋아보입니다.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +}
오타 있네요

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
이 속성들은 default 값인데 왜 사용하신거죠? 제플린 속성 그대로 옮기지 마시고 이해해서 사용하세요.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  padding: 12px 0 11.5px 32px; ;
오타있습니다.

```suggestion
  padding: 12px 0 11.5px 32px;
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
같은 속성이 계속해서 반복되면서 사용되네요.
해당 속성은 `default` 속성이라 굳이 안써줘도 되지만,
만약 중복 속성이 계속 반복된다면 상속받아 사용하시면 됩니다.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
코드 중복은 왠만해선 하지마세요. DRY 원칙을 준수해주세요.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +        <Logo src="/asset/Group 1583.png" alt="Logo" />
`Group 1583` 의 의미가 뭐죠?? 딱 봤을 때 어떤 의미인지 이해할 수 있나요?
알아보기 쉬운 명칭으로 수정해주세요.
```suggestion
        <Logo src="/asset/logo.png" alt="Logo" />
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +        </KeywordDropmenu>
같은 컴포넌트가 반복되네요. map 을 사용해서 렌더링하게 수정해주세요.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  height: 1110px;
zeppelin 그대로 옮기신건가요...??  
본인 컴퓨터에서도 브라우저 높이가 `1110px` 이 넘어가면 navigation 바가 안닿을텐데, 
어떤 생각으로 고정 픽셀을 사용하신건가요?

이게 뭡니까...
<img width="642" alt="스크린샷 2021-12-02 오후 6 19 01" src="https://user-images.githubusercontent.com/19240202/144393175-fef8bab9-1262-47a1-82cd-e8137368ec76.png">

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
object-fit 속성에 대해 이해하고 사용하신 거 맞나요? 이 속성이 정말 필요한가요?

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  }};
이렇게 쓰는게 좋습니다.

```suggestion
  margin: ${({ sideMenu }) => sideMenu ? `289px 0 0 0 ` : `20px 0`}};
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  }};
다 위와 같이 수정하세요

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
아무리봐도 `object-fit` 속성에 대한 구체적인 이해없이 제플린 옮기신것 같은데, 아닌가요?

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  const [sideMenu, setsideMenu] = useState(false);
이건 camelCase 를 지키는것도 지키지 않는것도 아니네요.
변수명 제대로 사용하세요

```suggestion
  const [sideMenu, setSideMenu] = useState(false);
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  };
showSideMenu 는 오직 sideMenu를 보여주게 만드는 것 같은데,
현재 코드는 이전 상태를 계속해서 바꾸는 것으로 보입니다.
현 함수 이름을 유지하려면 로직을 바꾸던가, 이름을 바꾸세요.

```suggestion
  const showSideMenu = () => setSideMenu(true);
```

```suggestion
  const toggleSideMenu = () => {
    setSideMenu(prev => !prev);
  };
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +          <MenuButton type="button" onClick={() => showSideMenu()}>
함수에 인자가 없으면 함수 그대로 넘겨줘도 됩니다.
의미를 잘 생각해보세요

```suggestion
          <MenuButton type="button" onClick={showSideMenu}>
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +        </SetBlock>
확실하진 않지만, 같은 `Block` 이라는 도메인에 종속되어 있는 것 같습니다.
실제로 해당 식별자들을 확인해보니 공통 css 속성들이 많더라고요.
이를 하나의 `Block` 이라는 식별자를 만들어서 관리하고, 이를 감싸는 상위 컨테이너에서 레이아웃을 잡아주는 방법이 있습니다.

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +      {sideMenu ? <SidenavMenu /> : null}
이렇게 쓸거면 `&&` 연산자가 더 좋습니다.

```suggestion
      {sideMenu && <SidenavMenu />}
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/pages/chatPage.js
> +}
컴포넌트 PascalCase 로 작성하는 것은 스스로 정한 원칙 아니였나요?

```suggestion
function ChatPage() {
  return <div>chat</div>;
}
```

2021-12-02 09:36 UTC, jonghopark95 commented on yarn.lock
> +
이건 사용하지 않는거 같은데 왜 설치하셨나요?

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  const [sideMenu, setsideMenu] = useState(false);
다시보니 boolean 값인데 `sideMenu` 라는 변수명을 사용하셨네요.

`isSideMenu`가 더 좋지 않을까요?

2021-12-02 09:36 UTC, jonghopark95 commented on src/App.js
> +  <div className="Main">
왜 className 을 만들어주신거죠? 

```suggestion
  <div>
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/App.js
> +import myPage from 'pages/myPage';
페이지도 컴포넌트입니다... 다 수정하셔야겠네요.

```suggestion
import ChatPage from 'pages/ChatPage';
import HistoryPage from 'pages/HistoryPage';
import KeywordPage from 'pages/KeywordPage';
import MyPage from 'pages/MyPage';
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/App.js
> +import SideNavbar from 'components/SideNavbar/SideNavbar';
이렇게 사용하는거 뭔가 이상하지 않나요?
SideNavBar 폴더 내의 SideNavBar.js 파일명을 index.js 로 수정하면, 아래와 같이 import 할 수 있습니다.

```suggestion
import SideNavbar from 'components/SideNavbar';
```

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
중복되는 속성 꼭 제거하세요. 
폰트 요소들은 상위 요소에서 지정해주면 하위 요소에서 css 요소들을 상속받을 수 있습니다.
심지어 이 속성들은 기본값들이라 지정할 필요도 없네요. (font-weight 제외)

2021-12-02 09:36 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  }};
본인이 생각해도 변수명이 이상하지 않나요?
sideMenu 는 명사인데 boolean 처럼 사용되고 있습니다.

```suggestion
  ${({ isSideMenu }) => {
    return isSideMenu ? `margin :   397px 0 0 0 ` : `margin: 20px 0`;
  }};
```

2021-12-02 09:39 UTC, jonghopark95 commented
PR 제목이 `Feature/#4` 가 뭐죠...? 어떤 PR 인지 알아볼 수 있게 이름 수정해주세요

2021-12-02 09:41 UTC, daepan commented on yarn.lock
> +
이거 분명 제가 삭제했는데 한번 더 확인하겠습니다

2021-12-02 09:43 UTC, jonghopark95 commented
스스로 labels 만든거 왜 안쓰시나요
PR에 labels 추가해보세요

2021-12-02 09:46 UTC, jonghopark95 commented on yarn.lock
> +
`.lock` 파일도 학습하시길 바랍니다 `node_modules`, `package.json` 에서만 지운다고 끝나는게 아닙니다

2021-12-02 10:30 UTC, daepan commented on public/index.html
> +    <script type="text/javascript" src="vendor/jquery/jquery.js"></script>
return 오류 발생했을 때 시도 중에 올려둔 내용인데 삭제하지 않은 부분이였습니다. 삭제해두겠습니다.(완)

2021-12-02 10:31 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +import SidenavMenu from './SidenavMenu';
이번에 ESLint를 첫 사용이라 오류가 발생하면 찾고 하는 시간이 너무 오래걸려서 급하게 임시조치만 해두게됩니다.
잠시 ESLint 꺼두고 하겠습니다.

2021-12-02 10:34 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  height: 21px;
저도 그렇게 생각은 했는데 미루려고만 했습니다 ㅠㅠ. 이번에 해두겠습니다.

2021-12-02 10:35 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
이번에 만들면서 전체적으로 제플린 css코드에만 의존했던 것 같습니다. 제플린 코드를 어디까지 봐야할지 조금 저만의 시선을 만들어 보겠습니다.

2021-12-02 10:38 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
DRY - Don't Repeat Yourself 
 : 똑같은 일을 두번하지 않는다. 중복되는 함수나 코드는 하나의 공통의 콤포넌트에 넣고 사용한다. 큰 시스템을 여러 조각으로 나누고 서로 참조한다.
 같은 코드를 중복해서 작성하지 않는다. 시스템이 소규모일때는 복잡도가 크기 않기 때문에 프로그램을 이해하기가 수월한 반면 시스템이 커지고 개념도 많아지면 복잡도가 기하급수적으로 높아지게 된다. 이런 시스템에서는 복잡도를 최대한 줄여야 개발 및 나중에 유지보수비용이 절감이 된다. 

styled-components에 제플린 css 코드를 넣어야한다고 생각하니 이런코드가 반복됬습니다. 제플린에 너무 의지하지 않겠습니다.

2021-12-02 10:38 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +        <Logo src="/asset/Group 1583.png" alt="Logo" />
이미지 파일 이름 수정하겠습니다

2021-12-02 10:40 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  height: 1110px;
제플린을 맞춘다고 생각해보니...

2021-12-02 14:14 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
넵 맞습니다 조사하고 한번 더 확인해보겠습니다.

2021-12-02 14:17 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  const [sideMenu, setsideMenu] = useState(false);
camelCase가 잘 적용된 줄 알았는데 아직 미숙했습니다. 신경쓰겠습니다.

2021-12-02 14:19 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +import SidenavMenu from './SidenavMenu';
넵 코드에 주석으로 끄면 더럽게 보이니 eslint 설정 파일에서 꺼주세요~

2021-12-02 14:20 UTC, daepan commented on src/App.js
> +  <div className="Main">
일단 지금 테스트로만 올려두는 거라고 생각해서 나중에 App.js 수정 시에 변경하려고 임시로 만들어서 사용했습니다

2021-12-02 14:20 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  height: 21px;
넹 별로 어려운거 아니니 후딱 옮기셔요~~

2021-12-02 14:20 UTC, daepan commented on src/App.js
> +import myPage from 'pages/myPage';
pages도 컴포넌트 메모메모...

2021-12-02 14:20 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
넹 제플린 속성들은 참고용이지 의무가 아닙니다~

2021-12-02 14:21 UTC, pumpkiinbell commented on src/components/SideNavbar/SideNavbar.js
> +  height: 1110px;
다음 작업 전에 수정해주세요~

2021-12-02 14:21 UTC, jonghopark95 commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
좋습니다 아마 없어도 될거예요~

2021-12-02 14:25 UTC, jonghopark95 commented on src/App.js
> +import myPage from 'pages/myPage';
용어가 좀 애매하긴 한데... 중요한 것은 리액트 컴포넌트 형태로 만들어지는 모든 것들은 PascalCase 사용하는게 좋습니다 :)

2021-12-02 14:25 UTC, pumpkiinbell commented on src/App.js
> +  <div className="Main">
네...? 무슨 소리죠...? 뭘 테스트 하려고 하길래 `className` 사용한거죠?

2021-12-03 04:44 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +        </KeywordDropmenu>
이쪽은 아예 다른 컴포넌트로 분할했습니다.

2021-12-03 04:57 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +        </SetBlock>
Block 분할했습니다!

2021-12-03 04:59 UTC, daepan commented on src/App.js
> +  <div className="Main">
형식만 맞추려고 올렸습니다.  className 꼭 필요한 경우 아니면 사용자제하겠습니다

2021-12-03 05:00 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +        </KeywordDropmenu>
48283b2

2021-12-03 05:46 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +        </SetBlock>
092ef69

2021-12-03 06:18 UTC, daepan commented on public/index.html
> +    <script type="text/javascript" src="vendor/jquery/jquery.js"></script>
85471f1

2021-12-03 06:19 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +import SidenavMenu from './SidenavMenu';
7ed93d6

2021-12-03 06:20 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +}
2d819dd

2021-12-03 06:20 UTC, daepan commented on src/App.js
> +      <Route path="/mypage" component={myPage} exact />
cbfe814

2021-12-03 06:21 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  height: 21px;
49aefb5

2021-12-03 06:21 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
7ea0a85

2021-12-03 06:22 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +      {sideMenu ? <SidenavMenu /> : null}
725609a

2021-12-03 06:24 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  height: 1110px;
3759244
![image](https://user-images.githubusercontent.com/50792467/144555599-f5e5640d-7e00-4c54-8a13-6ab1638f5507.png)

2021-12-03 06:25 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  }};
092ef69

2021-12-03 06:25 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +          <MenuButton type="button" onClick={() => showSideMenu()}>
092ef69

2021-12-03 06:42 UTC, daepan commented on src/App.js
> +import SideNavbar from 'components/SideNavbar/SideNavbar';
index 파일로 수정했습니다(완)

2021-12-03 06:46 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  }};
변수명 수정했습니다(완)

2021-12-03 08:15 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  };
725609a 수정완료

2021-12-03 08:17 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  padding: 12px 0 11.5px 32px; ;
```
export const KeywordText = styled.div`
  width: 190px;
  height: 21px;
  padding: 12px 0 11.5px 32px;
`;
```
수정했습니다

2021-12-03 08:20 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
cc22161
styles.js 파일로 옮기고 공통된 속성 상속하는 방식으로 수정했습니다!

2021-12-03 08:20 UTC, daepan commented on src/pages/chatPage.js
> +}
Page == Component

2021-12-03 08:21 UTC, daepan commented on yarn.lock
> +
0af3d6d 삭제완료

2021-12-03 08:22 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  }};
725609a

2021-12-03 08:22 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  }};
725609a

2021-12-03 08:23 UTC, daepan commented on src/components/SideNavbar/SideNavbar.js
> +  object-fit: contain;
제플린 남발 하지 않겠습니다 ;;

2021-12-03 08:24 UTC, daepan commented on src/components/SideNavbar/SideNavMenu.js
> +  letter-spacing: normal;
지금 당장 필요한 속성이 아니여서 삭제했습니다

2021-12-03 08:33 UTC, daepan commented
올려두신 전체 리뷰에 대해 수정완료했고 댓글로 어떻게 수정하였는지 작성했습니다.

2021-12-03 08:35 UTC, jonghopark95 approved these changes
수고하셨습니다~

2021-12-03 09:38 UTC, merged