키워드 페이지 전체 스타일 수정
BCSDLab/KOALA_FRONT_END pull request #78
Opened 2022-04-23 15:41 UTC by daepan

## 개요 
![image](https://user-images.githubusercontent.com/50792467/164912795-c76b7aea-13d3-432b-ba62-93eaa7e680a5.png)
![image](https://user-images.githubusercontent.com/50792467/164912923-c15e7b7d-bbfd-4ff1-869d-f3d42dca6760.png)
![image](https://user-images.githubusercontent.com/50792467/164912843-0cd4a77c-2249-48d8-940d-642abc8f0318.png)
![image](https://user-images.githubusercontent.com/50792467/164912864-061ad406-1baa-41f8-8393-23996d069658.png)
![image](https://user-images.githubusercontent.com/50792467/164912887-e046ac8d-88b4-47a5-bab0-9e7ac9a4bf05.png)
![image](https://user-images.githubusercontent.com/50792467/164912913-d6be0550-cc00-4917-a50b-5962cca4598f.png)

## 이슈 번호

- closes [#67]

## 변경사항 
키워드 전체적으로 스타일 수정하는 작업을 진행하였습니다. 반응형으로 제작하여 거의 모든 화면에서 중앙정렬 혹은 화면이 깨지지 
않도록 조정하였습니다.
모바일 키워드 수정페이지가 제대로 작동하지 않아 수정하였습니다

## 특이사항 
스타일 위주로 봐주시고 기능상 문제 있는 경우 작성 부탁드립니다.

2022-04-24 14:18 UTC, ChoiWonBeen requested changes
몇몇 이미지의 src주소가 맞지 않아 이미지가 나오지 않는 경우가 꽤 보입니다.(당장만 봐도 3개의 파일에서 쓰이는 hashtagWhite, Hashtagblack)

svg파일의 네이밍 컨벤션을 전체적으로 맞춰야 할 듯 싶네요.

2022-04-24 14:18 UTC, ChoiWonBeen commented on src/components/Keyword/AddKeyword/index.js
>            <S.HashtageImage src="/asset/hashtagblack.svg" alt="hashtage_image" />
```suggestion
          <S.HashtageImage src="/asset/Hashtagblack.svg" alt="hashtag_image" />
```

이미지 주소가 안맞고, alt 이름도 수정이 필요해 보입니다.

2022-04-24 14:18 UTC, ChoiWonBeen commented on src/components/Keyword/AddKeyword/index.js
>            <S.HashtageImage src="/asset/hashtagblack.svg" alt="hashtage_image" />
여기 뿐 아니라 프로젝트 내에서 검색하면 '**HashTage**'라는 오타가 많이 나오는데 수정이 필요해 보이네요.

2022-04-24 14:18 UTC, ChoiWonBeen commented on src/components/Keyword/AddKeyword/index.js
> +                onChange={onChangeSite}
이게 디바운싱을 해둔 건 좋은데, 처음 사용해 본 입장으로 뭘 검색해야 하는 질 모르겠어요.
focus event때 동기적으로 모든 datalist가 나오는 게 좋지 않을까 싶어요

2022-04-25 05:16 UTC, daepan commented on src/components/Keyword/AddKeyword/index.js
>            <S.HashtageImage src="/asset/hashtagblack.svg" alt="hashtage_image" />
전체적으로 이미지 파일에 대한 네이밍은 수정을 진행하겠습니다

2022-04-25 05:18 UTC, daepan commented on src/components/Keyword/AddKeyword/index.js
> +                onChange={onChangeSite}
기획 팀에 이와 비슷한 내용을 전달한 적이 있는데 아직 큰 답장이 없었습니다

2022-06-04 06:58 UTC, ChoiWonBeen commented
와우 네이밍수정 고생했다 ㅋㅋㅋ

2022-07-08 13:46 UTC, SimYunSup approved these changes

2022-07-08 14:15 UTC, ChoiWonBeen approved these changes

2022-07-08 14:26 UTC, merged