로그인 관련 기능 추가
BCSDLab/KOALA_FRONT_END pull request #9
Opened 2021-12-13 06:26 UTC by daepan

## 개요 
![image](https://user-images.githubusercontent.com/50792467/145758582-5b9cd366-596b-4bdb-b9de-d1116ba90873.png)
![image](https://user-images.githubusercontent.com/50792467/145758619-016d1bbe-5110-4268-8d0b-4777456b3be1.png)
로그인과 로그아웃
## 이슈 번호

- closes [#8] 

## 변경사항 
로그인 시 access token은 state에 저장하고 refresh token은 cookie에 저장한다.
그리고 화면이 새로고침 혹은 이동할 때마다 refresh token으로 token들을 다시 받아오고 저장한다.
isLogined를 state에 저장함으로써 현재 로그인이 되어있는지를 확인하고 유지한다.
로그아웃시  state의 토큰과 cookie의 토큰을 전부 지우고 isLogined를 false로 만들어줘서 로그아웃을 한다.
## 특이사항

2021-12-13 14:02 UTC, jonghopark95 commented
할일이 많아 내일 밤이나 수요일에 리뷰해드릴 수 있을 것 같네요 ㅠㅠ 죄송합니당... 
여유가 된다면 코드 보면서 스스로 리팩토링 해보는 것도 좋을 듯 합니다.

2021-12-13 14:18 UTC, daepan commented
ㅠㅠㅠ 고생많으십니다. 오실 때까지 더 수정해보겠습니다

2021-12-14 08:14 UTC, jonghopark95 requested changes
우선 급하게 여기까지... 먼저 수정하고 있으셔용

2021-12-14 08:14 UTC, pumpkiinbell commented on src/components/Auth/Login.js
> +    e.preventDefault();
`change` 이벤트는 preventDefault 로 기본 이벤트를 막을 이유가 없습니다.

2021-12-14 08:14 UTC, pumpkiinbell commented on src/components/Auth/RegisterDoc.js
> +    navigate('/auth/createAccount');
`/auth/createAccount` 같은 path 들은 따로 `constants` 폴더에 `path` 객체를 만들어 관리할 수도 있어 보입니다.

2021-12-14 08:14 UTC, pumpkiinbell commented on src/components/Shared/Cookies.js
> +import { Cookies } from 'react-cookie';
cookie 관련 메서드를 쓰기 위해 굳이 `react-cookie` 의존성을 가져야 할 이유가 있을까요...?

[Document.cookie MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

2021-12-14 08:14 UTC, pumpkiinbell commented on src/pages/mainPage.js
> +  }, [isLogined]);
사용하지도 않는 `isTrued` 는 인자로 왜 받는 걸까요...? 더불어 의미없는 로직은 삼가주시길 바랍니당

```suggestion
  useEffect(() => setIsTrued(isLogined)}, [isLogined]);
```

2021-12-14 08:14 UTC, pumpkiinbell commented on src/pages/mainPage.js
> +  const [isTrued, setIsTrued] = useState(isLogined);
isLogined 를 전역 상태로 관리하고 있는데 왜 로컬 상태로 할당받아 다시 관리하는 거죠...?
Single of Truth 를 준수해주세요. 이는 상태에도 적용되는 말입니다.

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/auth.js
> +  isLogined: false,
`logined` 라는 처음 보는 표현이네요... `isLoggedIn` 이 더 좋아보입니다

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/auth.js
> +      authError: error,
다른 프로퍼티 처럼 authError 도 `initialState` 에 해당 프로퍼티와 기본값을 할당하고 사용하는 것이 좋아보입니다.

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/loading.js
> +const initialState = {};
여기도 해당 전역 공간이 어떤 프로퍼티를 갖는지 키와 기본값을 넣어주면 좋겠네요

2021-12-14 08:14 UTC, pumpkiinbell commented on src/pages/mainPage.js
> +  const [isTrued, setIsTrued] = useState(isLogined);
더불어 `isTrued`... 너무 이름이 어색합니다 변수명에 신경을 더 많이 써주세요

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/auth.js
> +  },
토큰을 상태로 가지는게 맞을...까요...? 토큰에 따라 화면 렌더링이 변할일이 있을까요...?

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/auth.js
> +  },
login input value 인것 같은데... 이걸 전역으로 관리할 이유가 있을까요?

2021-12-14 08:14 UTC, pumpkiinbell commented on src/store/auth.js
> +  },
reducer 에는 해당 값을 바꾸지도 않는 것 같습니다

2021-12-14 10:22 UTC, daepan commented on src/components/Shared/Cookies.js
> +import { Cookies } from 'react-cookie';
음... react-cookie를 사용하게된 것에서는 jwt token을 api header에 호출하기 편하게 하려고 Cookies.js 파일내에 쿠키에 관련된 함수를 저장해서 쿠키를 어느 파일에서든 쉽게 불러올 수 있게 하려고 찾은 방법입니다.  한번더 사용에 대해 고려해보겠습니다.

2021-12-14 11:37 UTC, daepan commented on src/pages/mainPage.js
> +  const [isTrued, setIsTrued] = useState(isLogined);
원래 로그인 이후 상태를 유지하기 위해 새로고침시 useEffect를 통해 refresh_token을 통해 새롭게 토큰 요청을 하게 하고 그에 대한 로그인 상태를 isLogined에서 true로 해둔 건데 새로고침 이후에 isLogined의 초깃값인 false를 먼저 읽고 이후에 true로 변경되어서 로그인/로그아웃 버튼의 상태가 유지되지않아 useState로 해당페이지에서 로그인 상태에 대한 정보를 갱신했습니다.  최대한 다시 보겠습니다 ㅠ

2021-12-14 11:38 UTC, daepan commented on src/store/auth.js
> +  isLogined: false,
네이밍이 또..

2021-12-14 12:55 UTC, daepan commented on src/components/Auth/Login.js
> +    e.preventDefault();
8b1a975

2021-12-14 12:56 UTC, daepan commented on src/pages/mainPage.js
> +  }, [isLogined]);
db5c7ad

2021-12-14 12:56 UTC, daepan commented on src/pages/mainPage.js
> +  const [isTrued, setIsTrued] = useState(isLogined);
db5c7ad

2021-12-15 05:59 UTC, daepan commented on src/store/auth.js
> +  },
6181777

2021-12-15 06:00 UTC, daepan commented on src/store/auth.js
> +  },
이미 로그인 usestate에서 관리하고 있었는데 방심한 것 같습니다.6181777

2021-12-15 06:00 UTC, daepan commented on src/store/auth.js
> +      authError: error,
6181777

2021-12-15 06:51 UTC, daepan commented on src/components/Auth/RegisterDoc.js
> +    navigate('/auth/createAccount');
13fe5c7

2021-12-15 08:15 UTC, daepan commented on src/store/loading.js
> +const initialState = {};
뷰컴포넌트 단에서 사용하는 것이 아니고 loading.js는 리덕스사가 사용할 때 API 요청을 쉽게하려고 작성한겁니다!

2021-12-16 09:10 UTC, jonghopark95 approved these changes
시간이 너무 지체되는 것 같아 approve 해놉니다
다만 수정할 부분은 수정하셔요

2021-12-16 09:10 UTC, jonghopark95 commented on src/api/unlogined.js
> +unlogined.defaults.baseURL = 'https://api.stage.koala.im/';
여긴 왜 .env 에 선언한 값 안사용하나요?

2021-12-16 09:10 UTC, jonghopark95 commented on src/api/unlogined.js
> +const unlogined = axios.create({});
인스턴스를 두개 분리한 이유가 뭔가요?

2021-12-16 09:10 UTC, jonghopark95 commented on src/api/logined.js
> +dotenv.config();
보통 이런 config 부분은 앱에서 최대한 빠르게 로드 되도록 index 부분이나 설정부에 선언합니다

2021-12-16 09:10 UTC, jonghopark95 commented on src/pages/mainPage.js
> +      )}
저번에도 말했지만 왜 굳이 전역 상태값을 받아와서 로컬에 넣고 사용하는지 모르겠습니다...

```suggestion
      {loginInfo.isLoggedIn ? (
        <LoginBtn onClick={logoutClick}>로그아웃</LoginBtn>
      ) : (
        <LoginBtn onClick={loginClick}>로그인</LoginBtn>
      )}
```

2021-12-16 10:34 UTC, daepan commented on src/api/unlogined.js
> +unlogined.defaults.baseURL = 'https://api.stage.koala.im/';
앗 확인하고 수정하겠습니다

2021-12-16 10:36 UTC, daepan commented on src/api/unlogined.js
> +const unlogined = axios.create({});
원래는 로그인상태와 비로그인 상태에서의 사용하는 경우도 있어서 비로그인 상태일때의 나오는 API 요청을 설계해둔겁니다

2021-12-16 10:38 UTC, jonghopark95 commented on src/api/unlogined.js
> +const unlogined = axios.create({});
굳이 그럴 필요가 있나요...?

2021-12-16 11:04 UTC, daepan commented on src/pages/mainPage.js
> +      )}
좀 제가 삽질 좀 시도해본겁니다,
저는 저런식으로 작성하면 로그아웃버튼이 바로 로그인 버튼으로 바뀔줄 알았는데 "새로고침을 해야된다"라는 것을 새로고침 안한 상태에서 바로 바꿀순 없진 않을까해서 생각하다가 로컬 변수랑 저런식으로 작성하니깐 바로 적용이 된다는 것을 알게됬슴다....

2021-12-16 11:16 UTC, daepan commented on src/api/logined.js
> +dotenv.config();
https://www.google.com/url?sa=i&url=http%3A%2F%2Fmisfits.kr%2F7707&psig=AOvVaw1nxH2QxuHMMfcPyGdxK350&ust=1639739800900000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPDM7_SY6PQCFQAAAAAdAAAAABAD

2021-12-16 11:17 UTC, daepan commented on src/api/logined.js
> +dotenv.config();
오옹닛

2021-12-16 11:19 UTC, daepan commented on src/api/unlogined.js
> +unlogined.defaults.baseURL = 'https://api.stage.koala.im/';
bb86c4a

2021-12-16 11:28 UTC, daepan commented on src/api/unlogined.js
> +const unlogined = axios.create({});
음어...... 굳이?를 따져보면 안 굳이 인것같군용

2021-12-16 11:31 UTC, daepan commented on src/api/unlogined.js
> +const unlogined = axios.create({});
048d4ce

2021-12-16 11:31 UTC, daepan commented on src/api/logined.js
> +dotenv.config();
db8f4f3

2021-12-16 11:31 UTC, daepan commented on src/pages/mainPage.js
> +      )}
18ce553

2021-12-16 11:36 UTC, daepan commented on src/store/auth.js
> +  isLogined: false,
수정완료

2021-12-16 12:16 UTC, daepan commented on src/components/Shared/Cookies.js
> +import { Cookies } from 'react-cookie';
6b69313

2021-12-16 12:17 UTC, daepan commented on src/components/Shared/Cookies.js
> +import { Cookies } from 'react-cookie';
쿠키의 기본을 사용하는 방법보다는 라이브러리에 너무 의존하려 했던것 같습니다 ㅠ

2021-12-16 12:18 UTC, daepan commented
수정할 부분은 전부 수정완료했습니다!

2021-12-17 05:07 UTC, merged